// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/repository.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	XmlRepositoryService_GetEvolucaoPreco_FullMethodName     = "/repository.XmlRepositoryService/GetEvolucaoPreco"
	XmlRepositoryService_GetRankingDominancia_FullMethodName = "/repository.XmlRepositoryService/GetRankingDominancia"
	XmlRepositoryService_GetPrecoMedio_FullMethodName        = "/repository.XmlRepositoryService/GetPrecoMedio"
)

// XmlRepositoryServiceClient is the client API for XmlRepositoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XmlRepositoryServiceClient interface {
	GetEvolucaoPreco(ctx context.Context, in *EvolucaoPrecoRequest, opts ...grpc.CallOption) (*EvolucaoPrecoResponse, error)
	GetRankingDominancia(ctx context.Context, in *RankingDominanciaRequest, opts ...grpc.CallOption) (*RankingDominanciaResponse, error)
	GetPrecoMedio(ctx context.Context, in *PrecoMedioRequest, opts ...grpc.CallOption) (*PrecoMedioResponse, error)
}

type xmlRepositoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewXmlRepositoryServiceClient(cc grpc.ClientConnInterface) XmlRepositoryServiceClient {
	return &xmlRepositoryServiceClient{cc}
}

func (c *xmlRepositoryServiceClient) GetEvolucaoPreco(ctx context.Context, in *EvolucaoPrecoRequest, opts ...grpc.CallOption) (*EvolucaoPrecoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvolucaoPrecoResponse)
	err := c.cc.Invoke(ctx, XmlRepositoryService_GetEvolucaoPreco_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xmlRepositoryServiceClient) GetRankingDominancia(ctx context.Context, in *RankingDominanciaRequest, opts ...grpc.CallOption) (*RankingDominanciaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RankingDominanciaResponse)
	err := c.cc.Invoke(ctx, XmlRepositoryService_GetRankingDominancia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xmlRepositoryServiceClient) GetPrecoMedio(ctx context.Context, in *PrecoMedioRequest, opts ...grpc.CallOption) (*PrecoMedioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrecoMedioResponse)
	err := c.cc.Invoke(ctx, XmlRepositoryService_GetPrecoMedio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XmlRepositoryServiceServer is the server API for XmlRepositoryService service.
// All implementations must embed UnimplementedXmlRepositoryServiceServer
// for forward compatibility.
type XmlRepositoryServiceServer interface {
	GetEvolucaoPreco(context.Context, *EvolucaoPrecoRequest) (*EvolucaoPrecoResponse, error)
	GetRankingDominancia(context.Context, *RankingDominanciaRequest) (*RankingDominanciaResponse, error)
	GetPrecoMedio(context.Context, *PrecoMedioRequest) (*PrecoMedioResponse, error)
	mustEmbedUnimplementedXmlRepositoryServiceServer()
}

// UnimplementedXmlRepositoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedXmlRepositoryServiceServer struct{}

func (UnimplementedXmlRepositoryServiceServer) GetEvolucaoPreco(context.Context, *EvolucaoPrecoRequest) (*EvolucaoPrecoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvolucaoPreco not implemented")
}
func (UnimplementedXmlRepositoryServiceServer) GetRankingDominancia(context.Context, *RankingDominanciaRequest) (*RankingDominanciaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRankingDominancia not implemented")
}
func (UnimplementedXmlRepositoryServiceServer) GetPrecoMedio(context.Context, *PrecoMedioRequest) (*PrecoMedioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPrecoMedio not implemented")
}
func (UnimplementedXmlRepositoryServiceServer) mustEmbedUnimplementedXmlRepositoryServiceServer() {}
func (UnimplementedXmlRepositoryServiceServer) testEmbeddedByValue()                              {}

// UnsafeXmlRepositoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XmlRepositoryServiceServer will
// result in compilation errors.
type UnsafeXmlRepositoryServiceServer interface {
	mustEmbedUnimplementedXmlRepositoryServiceServer()
}

func RegisterXmlRepositoryServiceServer(s grpc.ServiceRegistrar, srv XmlRepositoryServiceServer) {
	// If the following call panics, it indicates UnimplementedXmlRepositoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&XmlRepositoryService_ServiceDesc, srv)
}

func _XmlRepositoryService_GetEvolucaoPreco_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvolucaoPrecoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XmlRepositoryServiceServer).GetEvolucaoPreco(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XmlRepositoryService_GetEvolucaoPreco_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XmlRepositoryServiceServer).GetEvolucaoPreco(ctx, req.(*EvolucaoPrecoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XmlRepositoryService_GetRankingDominancia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankingDominanciaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XmlRepositoryServiceServer).GetRankingDominancia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XmlRepositoryService_GetRankingDominancia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XmlRepositoryServiceServer).GetRankingDominancia(ctx, req.(*RankingDominanciaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XmlRepositoryService_GetPrecoMedio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrecoMedioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XmlRepositoryServiceServer).GetPrecoMedio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XmlRepositoryService_GetPrecoMedio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XmlRepositoryServiceServer).GetPrecoMedio(ctx, req.(*PrecoMedioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// XmlRepositoryService_ServiceDesc is the grpc.ServiceDesc for XmlRepositoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var XmlRepositoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "repository.XmlRepositoryService",
	HandlerType: (*XmlRepositoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEvolucaoPreco",
			Handler:    _XmlRepositoryService_GetEvolucaoPreco_Handler,
		},
		{
			MethodName: "GetRankingDominancia",
			Handler:    _XmlRepositoryService_GetRankingDominancia_Handler,
		},
		{
			MethodName: "GetPrecoMedio",
			Handler:    _XmlRepositoryService_GetPrecoMedio_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/repository.proto",
}
