// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/repository.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvolucaoPrecoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvolucaoPrecoRequest) Reset() {
	*x = EvolucaoPrecoRequest{}
	mi := &file_proto_repository_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvolucaoPrecoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvolucaoPrecoRequest) ProtoMessage() {}

func (x *EvolucaoPrecoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repository_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvolucaoPrecoRequest.ProtoReflect.Descriptor instead.
func (*EvolucaoPrecoRequest) Descriptor() ([]byte, []int) {
	return file_proto_repository_proto_rawDescGZIP(), []int{0}
}

func (x *EvolucaoPrecoRequest) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *EvolucaoPrecoRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *EvolucaoPrecoRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type EvolucaoPrecoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*EvolucaoPrecoItem   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvolucaoPrecoResponse) Reset() {
	*x = EvolucaoPrecoResponse{}
	mi := &file_proto_repository_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvolucaoPrecoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvolucaoPrecoResponse) ProtoMessage() {}

func (x *EvolucaoPrecoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repository_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvolucaoPrecoResponse.ProtoReflect.Descriptor instead.
func (*EvolucaoPrecoResponse) Descriptor() ([]byte, []int) {
	return file_proto_repository_proto_rawDescGZIP(), []int{1}
}

func (x *EvolucaoPrecoResponse) GetItems() []*EvolucaoPrecoItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type EvolucaoPrecoItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Preco         float64                `protobuf:"fixed64,2,opt,name=preco,proto3" json:"preco,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvolucaoPrecoItem) Reset() {
	*x = EvolucaoPrecoItem{}
	mi := &file_proto_repository_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvolucaoPrecoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvolucaoPrecoItem) ProtoMessage() {}

func (x *EvolucaoPrecoItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repository_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvolucaoPrecoItem.ProtoReflect.Descriptor instead.
func (*EvolucaoPrecoItem) Descriptor() ([]byte, []int) {
	return file_proto_repository_proto_rawDescGZIP(), []int{2}
}

func (x *EvolucaoPrecoItem) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *EvolucaoPrecoItem) GetPreco() float64 {
	if x != nil {
		return x.Preco
	}
	return 0
}

type RankingDominanciaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankingDominanciaRequest) Reset() {
	*x = RankingDominanciaRequest{}
	mi := &file_proto_repository_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankingDominanciaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankingDominanciaRequest) ProtoMessage() {}

func (x *RankingDominanciaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repository_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankingDominanciaRequest.ProtoReflect.Descriptor instead.
func (*RankingDominanciaRequest) Descriptor() ([]byte, []int) {
	return file_proto_repository_proto_rawDescGZIP(), []int{3}
}

func (x *RankingDominanciaRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RankingDominanciaResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Items         []*RankingDominanciaItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankingDominanciaResponse) Reset() {
	*x = RankingDominanciaResponse{}
	mi := &file_proto_repository_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankingDominanciaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankingDominanciaResponse) ProtoMessage() {}

func (x *RankingDominanciaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repository_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankingDominanciaResponse.ProtoReflect.Descriptor instead.
func (*RankingDominanciaResponse) Descriptor() ([]byte, []int) {
	return file_proto_repository_proto_rawDescGZIP(), []int{4}
}

func (x *RankingDominanciaResponse) GetItems() []*RankingDominanciaItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type RankingDominanciaItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Dominancia    float64                `protobuf:"fixed64,2,opt,name=dominancia,proto3" json:"dominancia,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankingDominanciaItem) Reset() {
	*x = RankingDominanciaItem{}
	mi := &file_proto_repository_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankingDominanciaItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankingDominanciaItem) ProtoMessage() {}

func (x *RankingDominanciaItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repository_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankingDominanciaItem.ProtoReflect.Descriptor instead.
func (*RankingDominanciaItem) Descriptor() ([]byte, []int) {
	return file_proto_repository_proto_rawDescGZIP(), []int{5}
}

func (x *RankingDominanciaItem) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *RankingDominanciaItem) GetDominancia() float64 {
	if x != nil {
		return x.Dominancia
	}
	return 0
}

type PrecoMedioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrecoMedioRequest) Reset() {
	*x = PrecoMedioRequest{}
	mi := &file_proto_repository_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrecoMedioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrecoMedioRequest) ProtoMessage() {}

func (x *PrecoMedioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repository_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrecoMedioRequest.ProtoReflect.Descriptor instead.
func (*PrecoMedioRequest) Descriptor() ([]byte, []int) {
	return file_proto_repository_proto_rawDescGZIP(), []int{6}
}

func (x *PrecoMedioRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *PrecoMedioRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type PrecoMedioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PrecoMedioItem      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrecoMedioResponse) Reset() {
	*x = PrecoMedioResponse{}
	mi := &file_proto_repository_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrecoMedioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrecoMedioResponse) ProtoMessage() {}

func (x *PrecoMedioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repository_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrecoMedioResponse.ProtoReflect.Descriptor instead.
func (*PrecoMedioResponse) Descriptor() ([]byte, []int) {
	return file_proto_repository_proto_rawDescGZIP(), []int{7}
}

func (x *PrecoMedioResponse) GetItems() []*PrecoMedioItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type PrecoMedioItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	PrecoMedio    float64                `protobuf:"fixed64,2,opt,name=preco_medio,json=precoMedio,proto3" json:"preco_medio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrecoMedioItem) Reset() {
	*x = PrecoMedioItem{}
	mi := &file_proto_repository_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrecoMedioItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrecoMedioItem) ProtoMessage() {}

func (x *PrecoMedioItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repository_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrecoMedioItem.ProtoReflect.Descriptor instead.
func (*PrecoMedioItem) Descriptor() ([]byte, []int) {
	return file_proto_repository_proto_rawDescGZIP(), []int{8}
}

func (x *PrecoMedioItem) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *PrecoMedioItem) GetPrecoMedio() float64 {
	if x != nil {
		return x.PrecoMedio
	}
	return 0
}

var File_proto_repository_proto protoreflect.FileDescriptor

const file_proto_repository_proto_rawDesc = "" +
	"\n" +
	"\x16proto/repository.proto\x12\n" +
	"repository\"R\n" +
	"\x14EvolucaoPrecoRequest\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\"L\n" +
	"\x15EvolucaoPrecoResponse\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.repository.EvolucaoPrecoItemR\x05items\"G\n" +
	"\x11EvolucaoPrecoItem\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05preco\x18\x02 \x01(\x01R\x05preco\"0\n" +
	"\x18RankingDominanciaRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"T\n" +
	"\x19RankingDominanciaResponse\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.repository.RankingDominanciaItemR\x05items\"O\n" +
	"\x15RankingDominanciaItem\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\x12\x1e\n" +
	"\n" +
	"dominancia\x18\x02 \x01(\x01R\n" +
	"dominancia\"7\n" +
	"\x11PrecoMedioRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"F\n" +
	"\x12PrecoMedioResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.repository.PrecoMedioItemR\x05items\"I\n" +
	"\x0ePrecoMedioItem\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\x12\x1f\n" +
	"\vpreco_medio\x18\x02 \x01(\x01R\n" +
	"precoMedio2\xa4\x02\n" +
	"\x14XmlRepositoryService\x12W\n" +
	"\x10GetEvolucaoPreco\x12 .repository.EvolucaoPrecoRequest\x1a!.repository.EvolucaoPrecoResponse\x12c\n" +
	"\x14GetRankingDominancia\x12$.repository.RankingDominanciaRequest\x1a%.repository.RankingDominanciaResponse\x12N\n" +
	"\rGetPrecoMedio\x12\x1d.repository.PrecoMedioRequest\x1a\x1e.repository.PrecoMedioResponseB%Z#xml-service/bridge-repository/protob\x06proto3"

var (
	file_proto_repository_proto_rawDescOnce sync.Once
	file_proto_repository_proto_rawDescData []byte
)

func file_proto_repository_proto_rawDescGZIP() []byte {
	file_proto_repository_proto_rawDescOnce.Do(func() {
		file_proto_repository_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_repository_proto_rawDesc), len(file_proto_repository_proto_rawDesc)))
	})
	return file_proto_repository_proto_rawDescData
}

var file_proto_repository_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_repository_proto_goTypes = []any{
	(*EvolucaoPrecoRequest)(nil),      // 0: repository.EvolucaoPrecoRequest
	(*EvolucaoPrecoResponse)(nil),     // 1: repository.EvolucaoPrecoResponse
	(*EvolucaoPrecoItem)(nil),         // 2: repository.EvolucaoPrecoItem
	(*RankingDominanciaRequest)(nil),  // 3: repository.RankingDominanciaRequest
	(*RankingDominanciaResponse)(nil), // 4: repository.RankingDominanciaResponse
	(*RankingDominanciaItem)(nil),     // 5: repository.RankingDominanciaItem
	(*PrecoMedioRequest)(nil),         // 6: repository.PrecoMedioRequest
	(*PrecoMedioResponse)(nil),        // 7: repository.PrecoMedioResponse
	(*PrecoMedioItem)(nil),            // 8: repository.PrecoMedioItem
}
var file_proto_repository_proto_depIdxs = []int32{
	2, // 0: repository.EvolucaoPrecoResponse.items:type_name -> repository.EvolucaoPrecoItem
	5, // 1: repository.RankingDominanciaResponse.items:type_name -> repository.RankingDominanciaItem
	8, // 2: repository.PrecoMedioResponse.items:type_name -> repository.PrecoMedioItem
	0, // 3: repository.XmlRepositoryService.GetEvolucaoPreco:input_type -> repository.EvolucaoPrecoRequest
	3, // 4: repository.XmlRepositoryService.GetRankingDominancia:input_type -> repository.RankingDominanciaRequest
	6, // 5: repository.XmlRepositoryService.GetPrecoMedio:input_type -> repository.PrecoMedioRequest
	1, // 6: repository.XmlRepositoryService.GetEvolucaoPreco:output_type -> repository.EvolucaoPrecoResponse
	4, // 7: repository.XmlRepositoryService.GetRankingDominancia:output_type -> repository.RankingDominanciaResponse
	7, // 8: repository.XmlRepositoryService.GetPrecoMedio:output_type -> repository.PrecoMedioResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_repository_proto_init() }
func file_proto_repository_proto_init() {
	if File_proto_repository_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_repository_proto_rawDesc), len(file_proto_repository_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_repository_proto_goTypes,
		DependencyIndexes: file_proto_repository_proto_depIdxs,
		MessageInfos:      file_proto_repository_proto_msgTypes,
	}.Build()
	File_proto_repository_proto = out.File
	file_proto_repository_proto_goTypes = nil
	file_proto_repository_proto_depIdxs = nil
}
