services:
  # ---------------------------------------------------
  # 1. WATCHER
  # ---------------------------------------------------
  - type: worker
    name: crypto-watcher
    env: node
    plan: free
    buildCommand: cd data-processor/watcher && npm install
    startCommand: cd data-processor/watcher && node src/index.js
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: RABBITMQ_URL
        sync: false
      - key: SUPABASE_RAW_BUCKET
        sync: false

  # ---------------------------------------------------
  # 2. ENRICHER
  # ---------------------------------------------------
  - type: worker
    name: crypto-enricher
    env: node
    plan: free
    buildCommand: cd data-processor/enricher && npm install
    startCommand: cd data-processor/enricher && node src/index.js
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: RABBITMQ_URL
        sync: false
      - key: CMC_API_KEY
        sync: false
      - key: SUPABASE_CONFIGS
        sync: false
      - key: SUPABASE_RAW_BUCKET
        sync: false
      - key: SUPABASE_PROCESSED_BUCKET
        sync: false

  # ---------------------------------------------------
  # 3. SENDER
  # ---------------------------------------------------
  - type: worker
    name: crypto-sender
    env: node
    plan: free
    buildCommand: cd data-processor/sender && npm install
    startCommand: cd data-processor/sender && node src/index.js
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: RABBITMQ_URL
        sync: false
      - key: XML_SERVICE_URL
        sync: false
      - key: XML_SERVICE_TOKEN
        sync: false
      - key: SUPABASE_PROCESSED_BUCKET
        sync: false
      - key: SUPABASE_CONFIGS
        sync: false
      - key: CLEANER_URL
        sync: false

  # ---------------------------------------------------
  # 4. CLEANER
  # ---------------------------------------------------
  - type: web
    name: crypto-cleaner
    env: node
    plan: free
    buildCommand: cd data-processor/cleaner && npm install
    startCommand: cd data-processor/cleaner && node src/index.js
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_RAW_BUCKET
        sync: false
      - key: SUPABASE_PROCESSED_BUCKET
        sync: false